version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "."
    schedule:
      interval: "daily"

#  - package-ecosystem: "python"
#    directory: "modules/"
#    schedule:
#      interval: "weekly"
