block-list-secret-scan: []
download-external-modules: false
evaluate-variables: true
#framework:
#- terraform
quiet: true
compact: true
skip-check:
- CKV_TF_1  # The suggestion to use git hashes instead of version numbers is wretched
directory:
- .
