name: Check Formatting

permissions:
  contents: read # for actions/checkout to fetch code
  #  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

on:
  push:

jobs:

  fmt_modules:
    name: Fmt
    runs-on: ubuntu-latest

    steps:

      - uses: hashicorp/setup-terraform@v2

      - uses: actions/checkout@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: false
